### ISSUE TITLE
Sample fails to run on Intel Windows Vulkan driver on HD530 iGPU..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/HelloVulkan#1]
I know, I know that's an AMD Project, but since it runs on Nvidia GPUs just wanted
 to mention it doesn't run on Intel Skylake iGPU Vulkan driver on Windows.. 
 don't know using Intel Linux Vulkan driver which curiously is also named Anvil as your framework :-)
 may test later..
on Windows on debug mode I must comment:
assert (swapChainImageCount < surfaceCapabilities.maxImageCount);
since surfaceCapabilities.maxImageCount=0 for whatever reason..
anyway in release mode this doesn't matter
it crashes 
vkCmdBindIndexBuffer (commandBuffer, indexBuffer_, 0, VK_INDEX_TYPE_UINT32);
on function void VulkanQuad::RenderImpl 
with:
Exception thrown at 0x00007FFD4F1FFAFA (igvk64.dll) in HelloVulkan_Release_2015.exe: 
0xC0000005: Access violation reading location 0x0000000000000050.

**Comment by Anteru** [comment]
You're right, the assert is wrong, as `maxImageCount = 0` implies that there is no limited. I'll fix that right away. I'm not sure why it crashes when binding the index buffer. Can you check if the index buffer is created successfully?

**Comment by Anteru** [comment]
The index buffer offset was not taking the alignment requirements into account - fixed that. Should work now! Thanks for reporting!
