### ISSUE TITLE
Texturing sample does not work on devices with no combined device_local and host_visible memory type

### ISSUE THREAD

**Issue by SaschaWillems** [GPUOpen-LibrariesAndSDKs/HelloVulkan#3]
In [this line](https://github.com/GPUOpen-LibrariesAndSDKs/HelloVulkan/blob/master/hellovulkan/src/VulkanTexturedQuad.cpp#L395) the texture sample requests a buffer that is device local and host visible.

On devices that don't offer such a memory type (e.g. NVIDIA desktop GPUs) this will result in a crash as no memory is allocated. Those devices would need staging for this to work, or have the vertex data stored in a device local buffer.

**Comment by Anteru** [comment]
Thanks, good find. I'll take a look.
