### ISSUE TITLE
Barrier for local device buffer question.

### ISSUE THREAD

**Issue by nikitablack** [GPUOpen-LibrariesAndSDKs/HelloVulkan#4]
Hello,
Is it a typo in function `VulkanTexturedQuad::CreateMeshBuffers` in barrier specification? Here you're setting the source stage as `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` and destination stage as `VK_PIPELINE_STAGE_TRANSFER_BIT`. Shouldn't it be the other way around? As I see it, if (for the vertex buffer, for example) the pipeline reached a point where it needs to read a vertex (`dstAccessMask = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT`) it can get the wrong data because `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` stage already passed even if transfer was not completed. Even more, the documentation mentions that `VK_ACCESS_TRANSFER_WRITE_BIT` access can happen only in `VK_PIPELINE_STAGE_TRANSFER_BIT` stage which is definitely lower that `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT`. And even even more - the layers are complaining:

> layer DS: vkCmdPipelineBarrier(): pBufferMemBarriers[0].srcAccessMask (0x1000) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
> layer DS: vkCmdPipelineBarrier(): pBufferMemBarriers[0].dstAccessMask (0x4) is not supported by dstStageMask (0x1000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)

Upd.: and for the `VulkanQuad::CreateMeshBuffers` you're not using any barriers at all and I could't find any waiting for idle queue or device. Why?

**Comment by Anteru** [comment]
Sorry I didn't see this earlier. The vertex buffers etc. don't need a further sync, because the work only kicks off after the CPU side is done (notice they're in CPU memory in VulkanQuad, but in GPU memory in VulkanTexturedQuad, and hence that needs a barrier.) I just checked with VK SDK 1.1.73 and the validation layer is not complaining. I agree that this barrier looks dubious and I should probably check it once more, it should be transfer as src and vertex input as dst. I'll get to that - thanks!

**Comment by Anteru** [comment]
All fixed in 2575360ce8cf0393d5797fc80ca4b749a1b01d08, thanks!
